export default [
    [
        {
            title:"昨日结余",
            data:"$1,206,469,44"
        },
        {
            title:"昨日入金",
            data:"$20,000"
        },
        {
            title:"昨日结余",
            data:"$-12,206,44"
        },
        {
            title:"昨日浮动盈/亏",
            data:"$-21,206,65"
        }
    ],
    [
        {
            title:"注册用户",
            data:"1,206"
        },
        {
            title:"新注册",
            data:"20",
            choose: "true"
        },
        {
            title:"正式账户",
            data:"802"
        },
        {
            title:"交易账户",
            data:"2,342"
        }
    ],
    [
        {
            title:"用户待处理",
            data:"40"
        },
        {
            title:"入金待处理",
            data:"10"
        },
        {
            title:"出金待处理",
            data:"0"
        },
        {
            title:"未通过审批",
            data:"20"
        }
    ]
]
    
